name = "cloudflare-worker-go"
type = "javascript"
main = "src/index.js"

[build]
command = "GOOS=js GOARCH=wasm go build -o main.wasm"
upload_format = "modules"

[site]
compatibility_date = "2024-05-19"
bucket = "./pkg"

[env.production]
workers_dev = true

[env.production.vars]
  GOOGLE_CLOUD_FUNCTION_URL = "$GOOGLE_CLOUD_FUNCTION_URL"