name = "domyikado"
main = "src/index.js"
compatibility_date = "2024-05-19"

[build]
command = "GOOS=js GOARCH=wasm go build -o ./pkg/main.wasm"

[site]
bucket = "./pkg"

[env.production]
workers_dev = false
zone_id = "$ZONE_ID"
routes = ["$DOMAIN_MATCH"]

[env.production.vars]
  GOOGLE_CLOUD_FUNCTION_URL = "$GOOGLE_CLOUD_FUNCTION_URL"