name = "domyikado"
zone_id = "$ZONE_ID"
compatibility_date = "2024-05-19"

[env.production]
workers_dev = false
routes = ["$DOMAIN_MATCH"]

[env.production.vars]
  GOOGLE_CLOUD_FUNCTION_URL = "$GOOGLE_CLOUD_FUNCTION_URL"